-- *****************************************************************
-- created by Wei Shuai <cpuwolf@gmail.com> 2026-08-11
-- MobiFlight RfA107 / Rowsfire A107 V3 for iniBuilds A350
-- MSFS RPN from: Rowsfire-A107 V3.0-IniB A350.mfproj
-- *****************************************************************
if ilua_require_inibuild_a350() then return end

-- Do not remove below lines: hardware detection
local rfa107 = com.sim.mf.RfA107.Open()
if not rfa107 then return end
-- Do not remove above lines: hardware detection

uluaLog('MobiFlight RfA107 for iniBuilds A350')

-- ===========================================================
-- button binding (keysmap bits from mobiflight/rf_a107.json)
-- Note: mfproj AnalogInput INT LT FLOOD FCU (pot) has no CfgAnalog yet — skipped

-- FIRE-APU (bit 0)
rfa107:CfgRpn(0, '1 (>L:INI_FIRE_APU_FIRE_PB)', '0 (>L:INI_FIRE_APU_FIRE_PB)')

-- FIRE-ENG1 (bit 1)
rfa107:CfgRpn(1, '1 (>L:INI_FIRE_ENG_1_FIRE_PB)', '0 (>L:INI_FIRE_ENG_1_FIRE_PB)')

-- CALLS ALL (bit 2)
rfa107:CfgRpn(2, '1 (>L:INI_CALLS_FWD) 2 (>B:AIRLINER_CALLS_ALL_PUSH)', '(>B:AIRLINER_CALLS_ALL_RELEASE)')

-- FIRE TEST ENG2 (bit 3)
rfa107:CfgRpn(3, '1 (>L:INI_FIRE_TEST)', '0 (>L:INI_FIRE_TEST)')

-- FIRE TEST APU (bit 4)
rfa107:CfgRpn(4, '1 (>L:INI_FIRE_TEST)', '0 (>L:INI_FIRE_TEST)')

-- FIRE TEST ENG1 (bit 5)
rfa107:CfgRpn(5, '1 (>L:INI_FIRE_TEST)', '0 (>L:INI_FIRE_TEST)')

-- PUMPS-R STBY (bit 6)
rfa107:CfgRpn(6, '1 (>L:INI_OUTER_TANK_RIGHT)', '0 (>L:INI_OUTER_TANK_RIGHT)')

-- PUMPS-R MAIN (bit 7)
rfa107:CfgRpn(7, '1 (>L:INI_INNER_TANK_RIGHT)', '0 (>L:INI_INNER_TANK_RIGHT)')

-- PUMPS-R (bit 8)
rfa107:CfgRpn(8, '1 (>L:INI_CENTER_TANK_RIGHT)', '0 (>L:INI_CENTER_TANK_RIGHT)')

-- PUMP-CENTER TANK (bit 9)
rfa107:CfgRpn(9, '1 (>L:INI_FUEL_CTR_TANK_FEED_MAN)', '0 (>L:INI_FUEL_CTR_TANK_FEED_MAN)')

-- PUMPS-L (bit 10)
rfa107:CfgRpn(10, '1 (>L:INI_CENTER_TANK_LEFT)', '0 (>L:INI_CENTER_TANK_LEFT)')

-- PUMPS -L STBY (bit 11)
rfa107:CfgRpn(11, '1 (>L:INI_INNER_TANK_LEFT)', '0 (>L:INI_INNER_TANK_LEFT)')

-- PUMPS -L  MAIN (bit 12)
rfa107:CfgRpn(12, '1 (>L:INI_OUTER_TANK_LEFT)', '0 (>L:INI_OUTER_TANK_LEFT)')

-- EXT POWER (bit 13)
rfa107:CfgRpn(13, '(L:INI_GEN_EXT_A_ONLINE) ! (>L:INI_GEN_EXT_A_ONLINE) (L:INI_GEN_EXT_B_ONLINE) ! (>L:INI_GEN_EXT_B_ONLINE)')

-- BAT2 (bit 14)
rfa107:CfgRpn(14, '1 (>L:INI_BATTERY_2_SWITCH) 1 (>L:INI_BATTERY_EMER2_SWITCH)', '0 (>L:INI_BATTERY_2_SWITCH) 0 (>L:INI_BATTERY_EMER2_SWITCH)')

-- BAT1 (bit 15)
rfa107:CfgRpn(15, '1 (>L:INI_BATTERY_1_SWITCH) 1 (>L:INI_BATTERY_EMER1_SWITCH)', '0 (>L:INI_BATTERY_1_SWITCH) 0 (>L:INI_BATTERY_EMER1_SWITCH)')

-- STROBE OFF/AUTO (bit 16)
rfa107:CfgRpn(16, '2 (>L:INI_LIGHTS_STROBE)', '1 (>L:INI_LIGHTS_STROBE)')

-- STROBE AUTO/ON (bit 17)
rfa107:CfgRpn(17, '0 (>L:INI_LIGHTS_STROBE)', '1 (>L:INI_LIGHTS_STROBE)')

-- BEACON (bit 18)
rfa107:CfgRpn(18, '1 (>L:INI_LIGHTS_BEACON)', '0 (>L:INI_LIGHTS_BEACON)')

-- WING (bit 19)
rfa107:CfgRpn(19, '1 (>L:INI_LIGHTS_WING)', '0 (>L:INI_LIGHTS_WING)')

-- NAV&LOGO OFF/1 (bit 20)
rfa107:CfgRpn(20, '2 (>L:INI_LIGHTS_LOGO) 2 (>L:INI_LIGHTS_NAV)', '1 (>L:INI_LIGHTS_NAV) 1 (>L:INI_LIGHTS_LOGO)')

-- NAV&LOGO 1/2 (bit 21)
rfa107:CfgRpn(21, '0 (>L:INI_LIGHTS_LOGO) 0 (>L:INI_LIGHTS_NAV)', '1 (>L:INI_LIGHTS_NAV) 1 (>L:INI_LIGHTS_LOGO)')

-- RWY TURN OFF ON (bit 22)
rfa107:CfgRpn(22, '1 (>L:INI_RWY_TURNOFF_R_SWITCH) 1 (>L:INI_RWY_TURNOFF_L_SWITCH)', '0 (>L:INI_RWY_TURNOFF_R_SWITCH) 0 (>L:INI_RWY_TURNOFF_L_SWITCH)')

-- LAND-L RTRCT/OFF (bit 23)
-- unbound in mfproj

-- LAND-L OFF/ON (bit 24)
rfa107:CfgRpn(24, '1 (>L:INI_LIGHTS_LANDING)', '0 (>L:INI_LIGHTS_LANDING)')

-- LAND-R RTRCT/OFF (bit 25)
-- unbound in mfproj

-- LAND-R OFF/ON (bit 26)
rfa107:CfgRpn(26, '1 (>L:INI_LIGHTS_LANDING)', '0 (>L:INI_LIGHTS_LANDING)')

-- NOSE TAXI/TO (bit 27)
rfa107:CfgRpn(27, '2 (>L:INI_LIGHTS_NOSE)', '1 (>L:INI_LIGHTS_NOSE)')

-- NOSE OFF/TAXI (bit 28)
rfa107:CfgRpn(28, '0 (>L:INI_LIGHTS_NOSE)', '1 (>L:INI_LIGHTS_NOSE)')

-- SEATBELTS ON (bit 29)
rfa107:CfgRpn(29, '1 (>L:INI_SEATBELTS_SWITCH)', '2 (>L:INI_SEATBELTS_SWITCH)')

-- NO SMOKING OFF/AUTO (bit 30)
rfa107:CfgRpn(30, '2 (>L:INI_NO_SMOKING_SWITCH)', '1 (>L:INI_NO_SMOKING_SWITCH)')

-- FIRE-ENG2 (bit 31)
rfa107:CfgRpn(31, '1 (>L:INI_FIRE_ENG_2_FIRE_PB)', '0 (>L:INI_FIRE_ENG_2_FIRE_PB)')

-- ICE ENG2 (bit 32)
rfa107:CfgRpn(32, '1 (>L:INI_ENG_ANTI_ICE2_STATE)', '0 (>L:INI_ENG_ANTI_ICE2_STATE)')

-- ICE ENG1 (bit 33)
rfa107:CfgRpn(33, '1 (>L:INI_ENG_ANTI_ICE1_STATE)', '0 (>L:INI_ENG_ANTI_ICE1_STATE)')

-- ICE WING (bit 34)
rfa107:CfgRpn(34, '1 (>L:INI_WING_ANTI_ICE1_STATE)', '0 (>L:INI_WING_ANTI_ICE1_STATE)')

-- APU START (bit 35)
rfa107:CfgRpn(35, '(L:INI_APU_START_BUTTON) ! (>L:INI_APU_START_BUTTON)')

-- APU MASTERSW (bit 36)
rfa107:CfgRpn(36, '1 (>L:INI_APU_MASTER_SWITCH)', '0 (>L:INI_APU_MASTER_SWITCH)')

-- PACK2 (bit 37)
rfa107:CfgRpn(37, '1 (>L:INI_AIR_PACK2_BUTTON)', '0 (>L:INI_AIR_PACK2_BUTTON)')

-- APU BLEED (bit 38)
rfa107:CfgRpn(38, '1 (>L:INI_AIR_BLEED_APU)', '0 (>L:INI_AIR_BLEED_APU)')

-- PACK1 (bit 39)
rfa107:CfgRpn(39, '1 (>L:INI_AIR_PACK1_BUTTON)', '0 (>L:INI_AIR_PACK1_BUTTON)')

-- PROBE WINDOW HEAT (bit 40)
rfa107:CfgRpn(40, '1 (>L:INI_PROBE_WINDOW_HEAT1_STATE)', '0 (>L:INI_PROBE_WINDOW_HEAT1_STATE)')

-- CREW OXYGEN SUPPLY (bit 41)
rfa107:CfgRpn(41, '1 (>L:INI_CREW_SUPPLY)', '0 (>L:INI_CREW_SUPPLY)')

-- GROUND CTL (bit 42)
rfa107:CfgRpn(42, '(L:INI_GND_CTL) ! (>L:INI_GND_CTL)')

-- IR3 (bit 43)
rfa107:CfgRpn(43, '(L:INI_IR3_STATE) ! (>L:INI_IR3_STATE)')

-- IR2 (bit 44)
rfa107:CfgRpn(44, '(L:INI_IR2_STATE) ! (>L:INI_IR2_STATE)')

-- IR1 (bit 45)
rfa107:CfgRpn(45, '(L:INI_IR1_STATE) ! (>L:INI_IR1_STATE)')

-- TERR (bit 46)
rfa107:CfgRpn(46, '(L:INI_GPWS_TERR_STATE) ! (>L:INI_GPWS_TERR_STATE)')

-- LDGFLAP3 (bit 47)
rfa107:CfgRpn(47, '(L:INI_GPWS_FLAP_MODE) ! (>L:INI_GPWS_FLAP_MODE)')

-- DOME LIGHT BRT (bit 48)
rfa107:CfgRpn(48, '100 (>L:INI_CKPT_LT_DOME)', '40 (>L:INI_CKPT_LT_DOME)')

-- DOME LIGHT DIM (bit 49)
rfa107:CfgRpn(49, '0 (>L:INI_CKPT_LT_DOME) 0 (>L:INI_HUD_BRIGHTNESS_LEFT)', '30 (>L:INI_CKPT_LT_DOME) 50 (>L:INI_HUD_BRIGHTNESS_LEFT)')

-- NO SMOKING AUTO/ON (bit 50)
rfa107:CfgRpn(50, '0 (>L:INI_SIGNS_NO_MOBILE) 0 (>L:INI_NO_SMOKING_SWITCH)', '2 (>L:INI_SIGNS_NO_MOBILE) 1 (>L:INI_NO_SMOKING_SWITCH)')

-- EMERGENCY EXIT OFF (bit 51)
rfa107:CfgRpn(51, '2 (>L:INI_EMER_EXIT_SWITCH)', '1 (>L:INI_EMER_EXIT_SWITCH)')

-- EMERGENCY EXIT ON (bit 52)
rfa107:CfgRpn(52, '0 (>L:INI_EMER_EXIT_SWITCH)', '1 (>L:INI_EMER_EXIT_SWITCH)')

-- ADIRS-1 OFF/NAV (bit 53)
rfa107:CfgRpn(53, '0 (>L:INI_IRS1_STATE)', '1 (>L:INI_IRS1_STATE)')

-- ADIRS-1 ATT (bit 54)
rfa107:CfgRpn(54, '2 (>L:INI_IRS1_STATE)', '1 (>L:INI_IRS1_STATE)')

-- ADIRS-3 OFF/NAV (bit 55)
rfa107:CfgRpn(55, '0 (>L:INI_IRS3_STATE)', '1 (>L:INI_IRS3_STATE)')

-- ADIRS-3 ATT (bit 56)
rfa107:CfgRpn(56, '2 (>L:INI_IRS3_STATE)', '1 (>L:INI_IRS3_STATE)')

-- ADIRS-2 OFF/NAV (bit 57)
rfa107:CfgRpn(57, '0 (>L:INI_IRS2_STATE)', '1 (>L:INI_IRS2_STATE)')

-- ADIRS-2 ATT (bit 58)
rfa107:CfgRpn(58, '2 (>L:INI_IRS2_STATE)', '1 (>L:INI_IRS2_STATE)')

-- AIR XBLEED CLOSE?AUTO (bit 59)
rfa107:CfgRpn(59, '0 (>L:INI_AIR_X_BLEED)', '1 (>L:INI_AIR_X_BLEED)')

-- AIR XBLEED AUTO/OPEN (bit 60)
rfa107:CfgRpn(60, '2 (>L:INI_AIR_X_BLEED)', '1 (>L:INI_AIR_X_BLEED)')

-- WIPER-FAST (bit 61)
rfa107:CfgRpn(61, '5 (>L:INI_WIPER_SWITCH_LEFT)', '4 (>L:INI_WIPER_SWITCH_LEFT)')

-- WIPER-OFF (bit 62)
rfa107:CfgRpn(62, '3 (>L:INI_WIPER_SWITCH_LEFT)', '4 (>L:INI_WIPER_SWITCH_LEFT)')

-- ===========================================================
-- Read data for lights (Get* — keep all channels)

rfa107:GetIr11('(L:INI_IR1_FAULT) (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- IR1-1
rfa107:GetAdirsOnBat('(L:INI_IRS_ON_BATTERY) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 0.1 * (L:INI_DC_LIGHTS_FAILURE) 10 * *') -- ADIRS ON BAT
rfa107:GetEng1Fire1('(L:INI_FIRE_ENG_1_FIRE) (L:INI_FIRE_TEST) 1 == or (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 0.5 * (L:INI_DC_LIGHTS_FAILURE) 10 * *') -- ENG1-FIRE-1
rfa107:GetAupFireLed('(L:INI_FIRE_APU_FIRE) (L:INI_FIRE_TEST) 1 == or (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 0.5 * (L:INI_DC_LIGHTS_FAILURE) 10 * *') -- AUP-FIRE-LED
rfa107:GetEng2Fire1('(L:INI_FIRE_ENG_2_FIRE) (L:INI_FIRE_TEST) 1 == or (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 0.5 * (L:INI_DC_LIGHTS_FAILURE) 10 * *') -- ENG2-FIRE-1
rfa107:GetLdgFlap32('(L:INI_GPWS_FLAP3_MODE)') -- LDG FLAP3-2
rfa107:GetRcdrGndCtl2('(L:INI_GND_CTL) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- RCDR GND CTL-2
rfa107:GetOxygenCrewSupply2('(L:INI_CREW_SUPPLY) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- OXYGEN CREW SUPPLY-2
rfa107:GetPumpLStby1('(L:INI_INNER_TANK_LEFT_FAULT) (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 1.5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-L-STBY-1
rfa107:GetIr12('(L:INI_IR1_STATE) ! (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- IR1-2
rfa107:GetIr31('(L:INI_IR3_FAULT) (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- IR3-1
rfa107:GetIr32('(L:INI_IR3_STATE) ! (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- IR3-2
rfa107:GetIr21('(L:INI_IR2_FAULT) (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- IR2-1
rfa107:GetIr22('(L:INI_IR2_STATE) ! (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- IR2-2
rfa107:GetPumpLMain1('(L:INI_OUTER_TANK_LEFT_FAULT) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 1.5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-L-MAIN-1
rfa107:GetPumpLMain2('(L:INI_OUTER_TANK_LEFT) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-L-MAIN-2
rfa107:GetPumpRMain1('(L:INI_INNER_TANK_RIGHT_FAULT) 1== (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-R-MAIN-1
rfa107:GetPumpLStby2('(L:INI_INNER_TANK_LEFT) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-L-STBY-2
rfa107:GetPumpL1('(L:INI_CENTER_TANK_LEFT_FAULT) (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-L-1
rfa107:GetPumpL2('(L:INI_CENTER_TANK_LEFT) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-L-2
rfa107:GetPumpCenterTank1('(L:INI_FUEL_CTR_TANK_FEED_FAULT) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- PUMP-CENTER-TANK-1
rfa107:GetPumpCenterTank2('(L:INI_FUEL_CTR_TANK_FEED_MAN) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- PUMP-CENTER-TANK-2
rfa107:GetPumpR1('(L:INI_CENTER_TANK_RIGHT_FAULT) (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-R-1
rfa107:GetPumpR2('(L:INI_CENTER_TANK_RIGHT) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-R-2
rfa107:GetExternalPwr1('(L:INI_GPU_AVAIL) (L:INI_GEN_EXT_A_ONLINE) (L:INI_GEN_EXT_B_ONLINE) + 2 < and (L:INI_ANNLT_SWITCH) 0 == or') -- EXTERNAL PWR-1
rfa107:GetPumpRMain2('(L:INI_INNER_TANK_RIGHT) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-R-MAIN-2
rfa107:GetPumpRStby1('(L:INI_OUTER_TANK_RIGHT_FAULT) (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-R-STBY-1
rfa107:GetPumpRStby2('(L:INI_OUTER_TANK_RIGHT) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- PUMP-R-STBY-2
rfa107:GetBat1Off('(L:INI_BATTERY_1_SWITCH) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- BAT1 OFF
rfa107:GetBat11('(L:INI_BATTERY_1_FAULT) (L:INI_BATTERY_EMER1_FAULT) or 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- BAT1-1
rfa107:GetBat22('(L:INI_BATTERY_2_SWITCH) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- BAT2-2
rfa107:GetBat21('(L:INI_BATTERY_2_FAULT) (L:INI_BATTERY_EMER2_FAULT) or 1 == (L:INI_ANNLT_SWITCH) 0 ==  + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- BAT2-1
rfa107:GetPack21('(L:INI_AIR_PACK2_FAULT) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- PACK2-1
rfa107:GetExternalPwr2('(L:INI_GEN_EXT_A_ONLINE) (L:INI_GEN_EXT_B_ONLINE) or (L:INI_ANNLT_SWITCH) 0 == or') -- EXTERNAL PWR-2
rfa107:GetProbeWindowHeat2('(L:INI_PROBE_WINDOW_HEAT1_STATE) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- PROBE WINDOW HEAT-2
rfa107:GetPack11('(L:INI_AIR_PACK1_FAULT) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- PACK1-1
rfa107:GetPack12('(L:INI_AIR_PACK1_BUTTON) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- PACK1-2
rfa107:GetApuBleed1('(L:INI_AIR_BLEED_APU_FAULT) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- APU BLEED-1
rfa107:GetApuBleed2('(L:INI_AIR_BLEED_APU) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- APU BLEED-2
rfa107:GetAntiIceEng21('(L:INI_ENG_ANTI_ICE2_FAULT) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- ANTI ICE ENG2-1
rfa107:GetPack22('(L:INI_AIR_PACK2_BUTTON) 0 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- PACK2-2
rfa107:GetApuMastersw1('(L:INI_APU_MASTER_FAULT) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_DC_LIGHTS_FAILURE) *') -- APU MASTERSW-1
rfa107:GetApuMastersw2('(L:INI_APU_MASTER_SWITCH) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 1 * * (L:INI_AC_LIGHTS_FAILURE) *') -- APU MASTERSW-2
rfa107:GetAntiIceWing1('(L:INI_WING_ANTI_ICE1_FAULT) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- ANTI ICE WING-1
rfa107:GetAntiIceWing2('(L:INI_WING_ANTI_ICE1_STATE) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- ANTI ICE WING-2
rfa107:GetAntiIceEng11('(L:INI_ENG_ANTI_ICE1_FAULT) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- ANTI ICE ENG1-1
rfa107:GetAntiIceEng12('(L:INI_ENG_ANTI_ICE1_STATE) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- ANTI ICE ENG1-2
rfa107:GetAntiIceEng22('(L:INI_ENG_ANTI_ICE2_STATE) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 5 * * (L:INI_AC_LIGHTS_FAILURE) *') -- ANTI ICE ENG2-2
rfa107:GetApuStart1('(L:INI_APU_AVAILABLE) 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 1 * * (L:INI_AC_LIGHTS_FAILURE) *') -- APU START-1
rfa107:GetApuStart2('(L:INI_APU_START_BUTTON) (L:INI_APU_AVAILABLE) ! and 1 == (L:INI_ANNLT_SWITCH) 0 == + 1 min (L:INI_GENERAL_LIGHT_MULTIPLIER) * 1 1 * * (L:INI_AC_LIGHTS_FAILURE) *') -- APU START-2
rfa107:GetEmerExitLt('(L:INI_EMER_EXIT_SWITCH) 0 ==') -- EMER EXIT LT
rfa107:GetA107Backlight('2.55 (L:INI_CKPT_LT_INTEG) *', 1) -- A107 BACKLIGHT

-- PAP3 LedModule BAT 1+2
rfa107:GetBat12('(L:INI_BATTERY_1_VOLTAGE)', '(L:INI_BATTERY_2_VOLTAGE)')

GlobalFrameLoopManager:add(function()
	rfa107:SetIr11()
	rfa107:SetAdirsOnBat()
	rfa107:SetEng1Fire1()
	rfa107:SetAupFireLed()
	rfa107:SetEng2Fire1()
	rfa107:SetLdgFlap32()
	rfa107:SetRcdrGndCtl2()
	rfa107:SetOxygenCrewSupply2()
	rfa107:SetPumpLStby1()
	rfa107:SetIr12()
	rfa107:SetIr31()
	rfa107:SetIr32()
	rfa107:SetIr21()
	rfa107:SetIr22()
	rfa107:SetPumpLMain1()
	rfa107:SetPumpLMain2()
	rfa107:SetPumpRMain1()
	rfa107:SetPumpLStby2()
	rfa107:SetPumpL1()
	rfa107:SetPumpL2()
	rfa107:SetPumpCenterTank1()
	rfa107:SetPumpCenterTank2()
	rfa107:SetPumpR1()
	rfa107:SetPumpR2()
	rfa107:SetExternalPwr1()
	rfa107:SetPumpRMain2()
	rfa107:SetPumpRStby1()
	rfa107:SetPumpRStby2()
	rfa107:SetBat1Off()
	rfa107:SetBat11()
	rfa107:SetBat22()
	rfa107:SetBat21()
	rfa107:SetPack21()
	rfa107:SetExternalPwr2()
	rfa107:SetProbeWindowHeat2()
	rfa107:SetPack11()
	rfa107:SetPack12()
	rfa107:SetApuBleed1()
	rfa107:SetApuBleed2()
	rfa107:SetAntiIceEng21()
	rfa107:SetPack22()
	rfa107:SetApuMastersw1()
	rfa107:SetApuMastersw2()
	rfa107:SetAntiIceWing1()
	rfa107:SetAntiIceWing2()
	rfa107:SetAntiIceEng11()
	rfa107:SetAntiIceEng12()
	rfa107:SetAntiIceEng22()
	rfa107:SetApuStart1()
	rfa107:SetApuStart2()
	rfa107:SetEmerExitLt()
	rfa107:SetA107Backlight()
	rfa107:SetBat12()
end)

